### ISSUE TITLE
text/ font size

### ISSUE THREAD

**Issue by ShinzonDK** [Skamer/Syling-Tracker#23] opened 2020-11-03 17:54 UTC
any way to ajust the font size its a bit to small for me to read it so whould be a nice thing to be able to ajust the font size if possible i use font size 14 to 16 depending what addon it is

**Comment by Skamer** [comment] 2020-11-04 09:39
It's in my plans, but currently i have no solution could be implemented easily and quickly for adding a way to do it. 

I close it as it's a Duplicate of #20

**Closed by Skamer** 2020-11-04 09:39 UTC
Labels: Enhancement
