### ISSUE TITLE
Achievement Tracking with kill # of mobs not updating.

### ISSUE THREAD

**Issue by Fizgig1973** [Skamer/Syling-Tracker#77] opened 2023-11-01 20:40 UTC
Achievement Tracking with kill # of mobs not updating.

Noticed this when tracking any achievements that need to have x amount of enemies killed. Does not update.

**Comment by Skamer** [comment] 2023-11-01 22:39
In the version (2.0.x) i'm developing, as the addon core has been almost completely rewritten, all modules had to be reworked, including the achievements as well. This is why it's possible the problem is fixed in my version. I'll check that, thanks for pointing that out.

**Closed** 2024-07-15 01:18 UTC
Labels: Bug
