### ISSUE TITLE
3 suggestions to improve Syling Tracker

### ISSUE THREAD

**Issue by Arkewas** [Skamer/Syling-Tracker#80] opened 2023-12-08 13:00 UTC
Hello,

I'm testing 2.0 version and Syling Tracker is becoming my favorite Objective Tracker. I especially like like the auto-sorting to the nearest quest objective and adding the feature to collapse the tracker's sections is surely a big improvement.

I would like that the following features would be implemented in Syling Tracker:

1) A single keyboard hotkey to alternately hide/show the tracker.
2) Automatically word wrap the objective text when it is too long for the tracker window.
3) A single left mouse click on the quest should open the quest details instead of right clicking and select "Show details"

Thank you and keep the good work.

**Comment by Skamer** [comment] 2023-12-08 14:54
I'm glad you enjoy the new version of the addon.

1. This is a good idea. I'm not very familiar with the Keybind API, but i have planned to learn more about it, as i also want to integrate keybinds for the item bar. The two ideas come together.
2. Isn't this already the case technically ?
3. This is an oversight on my part, as it was available in the previous version. It will be re-added as soon as possible.

**Comment by Arkewas** [comment] 2023-12-08 16:01
Also if I use the commands /slt hide and /slt show they show the tracker's option window but they don't hide or show the tracker.

**Comment by Skamer** [comment] 2023-12-08 19:51
I see, seems triggered on some font and font size. I need investigating about that, and will publish a fix once ready.

The commands are missing on this version, i'll re-add them.

**Comment by Arkewas** [comment] 2023-12-09 07:53
Thank you very much. About fonts I can only change font type not font size. Clicking on the slider or left / right arrows does nothing and this occurs for all tracker's options concerning fonts.

**Comment by Skamer** [comment] 2023-12-09 11:39
> Thank you very much. About fonts I can only change font type not font size. Clicking on the slider or left / right arrows does nothing and this occurs for all tracker's options concerning fonts.

This issue should be fixed  from a commit i pushed 1 week ago. What is the version you use ?

**Comment by Arkewas** [comment] 2023-12-09 12:04
I'm using version 2.0.0, officially released yesterday on Curseforge.

**Comment by Arkewas** [comment] 2023-12-09 13:02
The file CHANGELOG.md in my WoW addons folder displays:

# 2.0.0

Welcome to the v2. The addon has been rewritten from scratch with a new core.

**NEW**

- New contents: Collections, Recipe Tracker and Activities.
- Implemented POI icons.
- The Item Bar has been completely redevelopped. The row count, column count, item size, orientation, padding and margin can be changed from the options.
- The Mythic + module has been redone : new visual, and now supports the addon Mythic Dungeon Tools for displaying the pull percent.
- The trackers can now be minimized from a button.
- The contents can now be minimized.
- The tracker can be automatically hidden if no content is inside.
- Partial support of Widgets
- The scenario now display widgets if needed : this should display the timer of some events.
- Lot of new options have been added.

**CHANGES**

- Some tuning has been done in the visual for various elements.

**Comment by Skamer** [comment] 2023-12-09 13:53
The two best way for getting the exact version:
- From the minimap button tooltip.
- or From the options, located to bottom left.
![image](https://github.com/Skamer/Syling-Tracker/assets/849450/8d9a1ef1-6579-464a-9f67-d4410b7414f9)

**Comment by Arkewas** [comment] 2023-12-09 14:08
I opened the options window and the version is 2.0.0

**Comment by Skamer** [comment] 2023-12-09 18:50
The 2.0.2 bring back the slash commands and the left clicking to open the quest log for quests. I also fix the objective text wrap. 

About of slider buttons, i cannot reproduce the problem but i noticed the click hitbox is very very short.

**Comment by Arkewas** [comment] 2023-12-09 18:56
Thank you for your work. Where can I download 2.0.2 version?

**Comment by Skamer** [comment] 2023-12-09 19:13
> Thank you for your work. Where can I download 2.0.2 version?

Currently in the validation step on Curseforge, will be available as soon as passed it. Or you can grab it directly in the "Release" section on Github (this is the same package).

**Comment by Arkewas** [comment] 2023-12-09 19:41
Thanks, I've uninstalled version 2.0.0 and replaced it with version 2.0.2 downloaded from Github. Word wrapping works now but the command /slt hide does nothing. I still can't change font size but it's not so important as I can select a bigger font type.

**Comment by Arkewas** [comment] 2023-12-09 20:08
Clicking on a quest now opens Wow quest log, nice.

**Comment by Arkewas** [comment] 2023-12-10 10:15
The slash commands works.  They didn't worked before because i had enabled the macro [combat] hide; show in the Advanced Visibility rules. Removing "; show" fixed it.

**Comment by Arkewas** [comment] 2023-12-10 10:30
I'm glad  there's also the advanced option to automatically hide the tracker when in combat and restoring it when out of combat. I hope you can  implement the single hotkey to alternately hide/show the tracker. ATM I've created 2 macros with the commands /slt hide and /slt show, dragged them to a action bar and assigned 2 separate hotkeys to the 2 buttons.

**Comment by Skamer** [comment] 2023-12-10 10:34
> The slash commands works. They didn't worked before because i had enabled the macro [combat] hide; show in the Advanced Visibility rules. Removing "; show" fixed it.

Sorry for not giving more precision.

/slt hide or /slt show  changes the default visibility of tracker. This value is used by the system will automatically hide or show the tracker, it may be ignored depending of conditions you have used, so you can think the command don't work because this system do the opposite behavior. 
![image](https://github.com/Skamer/Syling-Tracker/assets/849450/e2cb5911-665b-4669-bb3b-7dae0f6dd676)

You can use the macro :`[combat] hide; default` 

In the previous version /slt hide and /slt show haven't the same behavior, this didn't change the default visibility, but disabled or enabled the tracker.  This behavior has been migrated to /slt enable and /slt disable.

```
--- `/slt enable` enable all the trackers and the item bar
--- `/slt enable all` the same as above 
--- `/slt enable itembar` enable only the itembar 
--- `/slt enable trackers` enable only all trackers
--- `/slt enable tracker main` enable only the main tracker 
--- `/slt enable tracker second` enable only the tracker with for id: second
```

**Comment by Arkewas** [comment] 2023-12-10 10:46
Thank you for the clarification, I'll use the macro [combat] hide; default as you suggest. From what I have been able to test so far Syling Tracker 2.0.2 works well, I'll continue to use it.

**Comment by Arkewas** [comment] 2023-12-10 11:40
Also the different colored background for Dungeons. Raids etc. and the fact you can change it if desired is a nice feature.

**Comment by Skamer** [comment] 2023-12-11 15:08
> Also the different colored background for Dungeons. Raids etc. and the fact you can change it if desired is a nice feature.

Will be included in the 2.0.4.
![image](https://github.com/Skamer/Syling-Tracker/assets/849450/0b63d596-3fd7-4b1b-bfa6-3ab235381b02)

 I also added options for changing the border and quest name colors for each quest type.

**Comment by Arkewas** [comment] 2023-12-11 15:23
Nice, thank you for time you spend for mantaining and improving Syling Tracker. It is more customizable than the default quest tracker and it works very well.

**Comment by Arkewas** [comment] 2023-12-11 15:25
I must add that the default quest tracker isn't customizable at all.

**Closed** 2024-03-23 10:09 UTC
Labels: Enhancement
